version: '3'
services:
  frontend-server:
    build: .
    environment: 
      - NODE_ENV=production
      - DDF_HOST_NAME=docker.for.mac.localhost
      - DDF_PORT=8993
      - EXPRESS_PORT=4000
    command: [
      "sh", 
      "-c", 
      "NODE_ENV=$${NODE_ENV} DDF_HOST_NAME=$${DDF_HOST_NAME} DDF_PORT=$${DDF_PORT} node bundle.middleware.js"
    ]
    ports:
      - '4000:4000'
