version: '3'
services:
  frontend-server:
    build: .
    environment:
      - NODE_ENV=production
      - DDF_LOCATION=https://docker.for.mac.localhost:8993
      - EXPRESS_PORT=3200
    command:
      [
        "sh",
        "-c",
        "NODE_ENV=$${NODE_ENV} DDF_LOCATION=$${DDF_LOCATION} EXPRESS_PORT=$${EXPRESS_PORT}} node bundle.middleware.js",
      ]
    ports:
      - "3200:3200"
